// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 15 May 2021 15:29:56 EEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package nk provides Go bindings for nuklear.h — a small ANSI C gui library.
*/
package nk
